# Generated by Django 2.0.4 on 2018-04-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=50)),
                ('buzz_word_one', models.CharField(default='', max_length=50)),
                ('buzz_word_two', models.CharField(default='', max_length=50)),
                ('buzz_word_three', models.CharField(default='', max_length=50)),
                ('buzz_word_four', models.CharField(default='', max_length=50)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
